### ISSUE TITLE
Provide Shortcut to AuthProviders & other Utils

### ISSUE THREAD

**Issue by lupas** [lupas/nuxt-fire#10]
### Problem
Below "util" functions are not yet accessible via nuxt-fire, so one has to import `import firebase from 'firebase/app'` manually where needed.

| Product | "Util" |
| --- | --- |
| Auth | new firebase.auth.FacebookAuthProvider() | 
| Auth | new firebase.auth.TwitterAuthProvider() | 
| Firestore | firebase.firestore.FieldValue.serverTimestamp() | 
| Firestore | new firebase.firestore.GeoPoint() | 
| Firestore | firebase.firestore.FieldPath.documentId() | 

and probably many more...

### Solution
Nuxt-fire could include this.$firebase as well, so the user could access these functions directly without having to import firebase/auth.

We could also include an option to toggle that:
`
includeFirebaseApp: true
`

**Comment by lupas** [comment]
Has been fixed for the fireAuth object in #24 , which can now be accessed via $fireAuthObj. If needed for any other please let me know.

**Comment by abegehr** [comment]
Definitely needed for new firebase.firestore.GeoPoint() 👍

**Comment by lupas** [comment]
@abegehr Alright. v1.4.0 should fix that for you :)

With v.1.4.0 you can now access the objects like so:

| Firebase Obj       | Shortcut         |
| ------------------ | ---------------- |
| firebase.auth      | \$fireAuthObj    |
| firebase.database  | \$fireDbObj      |
| firebase.firestore | \$fireStoreObj   |
| firebase.storage   | \$fireStorageObj |
| firebase.functions | \$fireFuncObj    |
| firebase.messaging | \$fireMessObj    |

Meaning `new this.$fireStoreObj.GeoPoint()` should work.

**Comment by DCSnip3r** [comment]
new this.$fireStoreObj.GeoPoint() is not working for me. Do these have to be imported in nuxt config? Or were there breaking changes with the new version?
