### ISSUE TITLE
Intellisense / AutoPredict

### ISSUE THREAD

**Issue by blowsie** [lupas/nuxt-fire#13]
Hi, 
Ive been using nuxt-fire and so far so good.
One small gripe, not a bug is that the Intellisense / AutoPredict / Completion is not working with my IDE.
In my case, webstorm.

I presume this is because the module is extending `this` / `app` and webstorm doesn't understand the context.

![image](https://user-images.githubusercontent.com/308572/48777850-9d842700-eccb-11e8-828a-55afd4afe8d3.png)

**Comment by lupas** [comment]
Thanks a lot for the issue!
Should be fixed with #16 with v1.2.1
