### ISSUE TITLE
$fireAuth not accesible from nuxtServerInit

### ISSUE THREAD

**Issue by liepaja** [lupas/nuxt-fire#18]
I am trying to access nuxt-fire instance within app, yet its not there. 
```
async nuxtServerInit ({ dispatch},{ req ,app}) {
    ....
    app.$fireAuth.auth()
});
```
`Cannot read property 'auth' of undefined`

Logging app confirms lack of instance.

**Comment by liepaja** [comment]
Ok, so issue was due to the fact that config was not fully set up. Even through i only used auth module and provided authKey, authDomain and projectId, it was not enough. After added the rest, its all good.

**Comment by lupas** [comment]
Great. Yes, the module currently expects you to input the entire Firebase config. Glad it works now.
