### ISSUE TITLE
Location selection for functions

### ISSUE THREAD

**Issue by liepaja** [lupas/nuxt-fire#19]
At the moment there is no way to select region. 
`var functions = firebase.app().functions('us-central1');`

this can be somehow specified in the initial config. Are PR of such sort welcome?

**Comment by lupas** [comment]
@liepaja 
Of course, thanks for the suggestion! Do you have time & wouldn't mind to do a PR for it? Otherwise I can try to implement that, but unfortunately won't have time before the weekend.

**Comment by lupas** [comment]
Has beeen implemented in [v1.4.1](https://github.com/lupas/nuxt-fire/releases/tag/v1.4.1) / 8141aba1fa0f4a51401b28f4379badf6b267e2e0 .

**Comment by kevinr90** [comment]
Is this implementation still active? It appears to have been removed from the documentation, and I can't seem to get it working?

**Comment by lupas** [comment]
@kevinr90 
It it still in the documentation [here](https://firebase.nuxtjs.org/guide/options/#functions), did you configure it like so?

If not, could you try that?

If it doesn't work let me know then I'll have a closer look.

**Comment by kevinr90** [comment]
Oops, obviously my CTRL+F skills aren't quite as honed as I thought.

Looks like I was referring to a possibly retired format for this (using a FunctionsLocation key)

I've amended to use this implementation and it works perfectly - sorry for not searching hard enough, and thanks for the _super speedy_ response!

**Comment by lupas** [comment]
@kevinr90 
No worries at all. Glad it works :)

Btw: The Algolia search at the top of the documentation is not that bad either ;)
