### ISSUE TITLE
What is the main difference with vuex-easy-firestore?

### ISSUE THREAD

**Issue by troublesprouter** [lupas/nuxt-fire#22]
I noticed there are two similar projects. I'm new to development. What's the main difference between this project and https://github.com/mesqueeb/vuex-easy-firestore ?

Thank you.

**Comment by lupas** [comment]
Hi @troublesprouter 

Please read the readme's of both projects carefully, it should be clear what they do.

Vuex-easy-firestore helps integrating Firebase's Firestore into your Vuex store, while nuxt-fire makes integrating any Firebase service into a Nuxt project easily.

So I wouldn't say there are similar at all.
