### ISSUE TITLE
Update peer dependency for firebase@6

### ISSUE THREAD

**Issue by lesharris** [lupas/nuxt-fire#25]
With the release of firebase 6.0.0 (and now 6.0.1) nuxt-fire's peer dependency is not met if firebase is upgraded.

Unless there's some reason for the peer dependency to be at 5.10.0 could it get updated?

**Comment by lupas** [comment]
@lesharris Please excuse the late response.

I just published v.1.3.2 (15c8c4a3420b4e25eeba093a201433cf6e0a56b4) that should fix the peer-dependency, thanks for the info.
