### ISSUE TITLE
Twitter Authentication with nuxt-fire

### ISSUE THREAD

**Issue by shmuelix** [lupas/nuxt-fire#29]
Does this plugin support Twitter login with Firebase & Nuxt ?
Couln't find anything in the code example / docs.

Thanks

**Comment by lupas** [comment]
@shmuelix 

Yes, this plugin allows to access **firebase.auth** which gives you access to Firebase's Twitter Authentication (among others).

See here:
https://firebase.google.com/docs/auth/web/twitter-login

You can access it like so:
```js
var provider = new this.$fireAuthObj.TwitterAuthProvider();

this.$fireAuth.signInWithPopup(provider).then(function(result) {
// and so on
}
```
