### ISSUE TITLE
Feature Request: Vuexfire integration example

### ISSUE THREAD

**Issue by miketierce** [lupas/nuxt-fire#30]
I recently tried to couple this nuxt-fire module to create a firestore instance that the vuexfire module could use to start the automatic 2-way binding of the firestore to the vuex state. 

However it seemed I was able to access `this.$fireStore` in the `bindFirestoreRef()` function called when initiating vuexfire. 

But within the same vuex store module before adding the vuexfire integration calling `this.$fireStore` worked without issue. 

I know this isn't an issue with nuxt-fire or probably even vuexfire I'm sure it's something in my setup and I haven't made it far enough yet to the kind of guy who can quickly setup a codepen/debugging environment. 

So I thought I would just rather request being that syncing the contents of the fire-store is the next natural step to take after using this library to so easily initialize firestore some documentation on how to use these tools together could help jumpstart a lot of new projects.

**Comment by lupas** [comment]
Hi @miketierce 
Thanks a lot for your feature request. I haven't used Vuexfire so far but it seems like many people would like to use nuxt-fire and vuexfire together. I'll have a look at it when I find the time, I'll keep you posted.

In the meantime let me know if you figure out on how to make these two modules work together.

**Comment by lupas** [comment]
@miketierce 

I tried a bit and made nuxt-fire work with vuexfire. I created the following example repository that showcases the use of . the two modules together:

[https://nuxt-fire-vuexfire.firebaseapp.com/](https://nuxt-fire-vuexfire.firebaseapp.com/)

I hope that helps :)
