### ISSUE TITLE
Add to firebaseopensource.com

### ISSUE THREAD

**Issue by samtstern** [lupas/nuxt-fire#33]
Someone suggested that we add your project to firebaseopensource.com 
https://github.com/firebase/firebaseopensource.com/issues/117

If that's something you're interested in, just file an issue on our GitHub and follow the instructions!

**Comment by lupas** [comment]
Thanks Sam, good idea! Will do as soon as possible :-)

**Comment by samtstern** [comment]
@lupas FYI I am going on vacation so don't be offended if I don't respond once you do it!  I'll get to it ASAP when I get back.

**Comment by lupas** [comment]
@samtstern no worries, I’m standing on a Volcano in Indonesia waiting for Sunrise as we speak, so I understand 😄 Enjoy your vacations!

**Comment by lupas** [comment]
Added with https://github.com/firebase/firebaseopensource.com/pull/119.

Waiting for merge.

**Comment by lupas** [comment]
@samtstern 
Added it quite a while ago and got it merged to master, but not yet showing up on firebaseopensource.com. Anything else to do on my side, or did you just not trigger the re-build yet?

**Comment by lupas** [comment]
Perfect, thanks! :)
