### ISSUE TITLE
Apps fail to load when Firebase Messaging is used in Safari

### ISSUE THREAD

**Issue by lesharris** [lupas/nuxt-fire#38]
Currently Nuxt-fire does not check to see if Firebase Messaging is actually supported before instantiating it.  This causes Safari to throw an Environment Not Supported exception which basically kills app loading.

Would be nice to get the check added so we don't have to fork nuxt-fire for our internal use. Thanks for maintaining this great package!

**Comment by lupas** [comment]
@lesharria

Good stuff, thanks!
Will only be on mobile for the next 24 hours, but will check & merge it as soon as possible!

Thanks a lot!

**Comment by lupas** [comment]
Merged and released on NPM in v2.0.1, thanks a lot! :)
