### ISSUE TITLE
Cannot read property 'development' of undefined 

### ISSUE THREAD

**Issue by xyllu** [lupas/nuxt-fire#39]
Hi!

This module is not working with latest nuxt version.
Error message:

 FATAL  Cannot read property 'development' of undefined                                                                                             16:26:26

  at ModuleContainer.nuxtFire (node_modules/nuxt-fire/index.js:23:48)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:190:34)
  at promise.then (node_modules/@nuxt/utils/dist/utils.js:1802:43)

(node:86421) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'development' of undefined
    at ModuleContainer.nuxtFire (/Users/danielhendricks/Apps/admin.ruklinikken.no/admin.ruklinikken.no/node_modules/nuxt-fire/index.js:23:48)
    at ModuleContainer.addModule (/Users/danielhendricks/Apps/admin.ruklinikken.no/admin.ruklinikken.no/node_modules/@nuxt/core/dist/core.js:190:34)
    at promise.then (/Users/danielhendricks/Apps/admin.ruklinikken.no/admin.ruklinikken.no/node_modules/@nuxt/utils/dist/utils.js:1802:43)
(node:86421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:86421) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any workarounds? Thank you :)

**Comment by lupas** [comment]
Hi @xyllu 

Are you sure it is due to the newer Nuxt version?
As you can see in the demo repository [nuxt-fire-demo](https://github.com/lupas/nuxt-fire-demo) it works fine with nuxt-fire 2.0.1 and nuxt 2.10.0.

Your error sounds like you have not properly set up your nuxt-fire module options in nuxt.config.js. Can you post your setup here?

It should look something like this:
```js
fire: {
    useOnly: [
      'auth',
      'firestore',
      'functions',
      'storage',
      'realtimeDb',
      'performance'
    ],
    functionsLocation: 'us-central1',
    config: {
      development: {
        apiKey: '...',
        authDomain: '...',
        databaseURL: '...',
        projectId: '...',
        storageBucket: '...',
        messagingSenderId: '...',
        appId: '...'
      },
      production: {
        apiKey: '...',
        authDomain: '...',
        databaseURL: '...',
        projectId: '...',
        storageBucket: '...',
        messagingSenderId: '...',
        appId: '...'
      }
    }
  }
```

**Comment by lupas** [comment]
Closed due to no reply - guess it’s been fixed.
