### ISSUE TITLE
Add support for Firebase Analytics

### ISSUE THREAD

**Issue by lesharris** [lupas/nuxt-fire#40]
Now that Firebase supports analytics for web apps [(What's new at Firebase Summit 2019)](https://firebase.googleblog.com/2019/09/Whats-new-at-Firebase-Summit-2019.html) it would be nice to include support for it in Nuxt-Fire.

**Comment by lupas** [comment]
Added with [v2.1.0](https://github.com/lupas/nuxt-fire/releases/tag/v2.1.0).

- [x] Pull Request merged
- [x] Readme.md updated
- [x] Release Notes added
- [x] Nuxt-Fire-Demo updated 
- [x] Published to NPM

Thanks @lesharris for the contribution, really appreciate it!
