### ISSUE TITLE
How to connect store/index.js

### ISSUE THREAD

**Issue by ruslanraupoff** [lupas/nuxt-fire#47]
Not found $fireAuth
```js
nuxtServerInit({ dispatch }) {
     const user = this.$fireAuth.currentUser
     dispatch('auth/setUser', user)
}
```

**Comment by fachri-adakerja** [comment]
@ruslanraupoff You can access it on the second parameter of `nuxtServerInit`
```js
nuxtServerInit({ dispatch }, ctx) {
     const user = ctx.$fireAuth.currentUser
     dispatch('auth/setUser', user)
}
```

**Comment by fachrihawari** [comment]
@ruslanraupoff You can access it on the second parameter of `nuxtServerInit`
```js
nuxtServerInit({ dispatch }, ctx) {
     const user = ctx.$fireAuth.currentUser
     dispatch('auth/setUser', user)
}
```

**Comment by lupas** [comment]
Hey guys

As you can see in the example in [nuxt-fire-demo](https://github.com/lupas/nuxt-fire-demo/blob/master/store/actions.js) both, **ctx** and **this** should actually work.

@ruslanraupoff
Let us know if both options don't work, then something with your vuex store setup might be wrong.

**Comment by ruslanraupoff** [comment]
@fachrihawari this absolutely return null 
```
nuxtServerInit({ dispatch }, ctx) {
     const user = ctx.app.$fireAuth.currentUser
     console.log(user)
     dispatch('auth/setUser', user)
}
```

**Comment by ruslanraupoff** [comment]
@lupas 
console Info
'Nuxt-fire Objects can be accessed in nuxtServerInit action via this.$fire___ and ctx.$fire___'

**Comment by lupas** [comment]
@ruslanraupoff 
`ctx.app.$fireAuth.currentUser` should also work, but `$fireAuth.currentUser` should work in the first place so not sure what is going on in your case.

Hard to tell why it is not working on your side, can you share your entire store action and nuxt.config.js files?

**Comment by ruslanraupoff** [comment]
@lupas 
store/index.js file
`
export const state = () => ({
    error: null
})

export const actions = {
    nuxtServerInit({ dispatch }) {
        const user = this.$fireAuth.currentUser
        console.log(user)
        dispatch('auth/setUser', user)
    }
}

export const mutations = {
    setError(state, error) {
        state.error = error
    },
    clearError(state) {
        state.error = null
    }
}

export const getters = {
    error: state => state.error
}
`
nuxt.config.js file
`
module.exports = {
  mode: 'universal',
  /*
  ** Headers of the page
  */
  head: {
    title: 'NYC Admin Panel',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: process.env.npm_package_description || '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#409EFF' },
  /*
  ** Global CSS
  */
  css: [
    'element-ui/lib/theme-chalk/index.css',
    '@/theme/index.scss'
  ],
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
    '@/plugins/axios',
    '@/plugins/globals',
    '@/plugins/element-ui'
  ],
  /*
  ** Nuxt.js dev-modules
  */
  buildModules: [
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    [
      'nuxt-fire',
      {
        // Required:
        config: {
          development: {
                ...
          },
          production: {
                ...
          }
        },
        // The following options are optional:
        useOnly: ['auth', 'firestore', 'functions', 'storage', 'realtimeDb', 'messaging', 'performance'],
        customEnv: false,
        functionsLocation: 'us-east4',
      }
    ]
  ],
  /*
  ** Axios module configuration
  ** See https://axios.nuxtjs.org/options
  */
  axios: {
  },
  
  env: {
    appName: 'Admin Panel'
  },

  /*
  ** Build configuration
  */
  build: {
    transpile: [/^element-ui/],
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
    }
  }
}
`

**Comment by lupas** [comment]
@ruslanraupoff 

Looks alright.

1) Does this.$fireAuth work in all other parts of your application, like your .vue file methods? If not, it's not because of nuxtServerInit but because of the setup.

2) I assume you defined the config values (...) properly? If not there should be an error message when building, stating that nuxt-fire has not properly been set up. Can you check if there is a message?

Hmm.... what could it be.. :O

**Comment by ruslanraupoff** [comment]
@lupas 
frontend side work brilliant only not working $fireAuth into store

**Comment by ruslanraupoff** [comment]
store/auth.js file login action is working
```
async login({ commit, dispatch }, formData) {
        try {
            await this.$fireAuth.signInWithEmailAndPassword(formData.email, formData.password)
                .then((firebaseUser) => {
                    //console.log(firebaseUser.user.uid)
                    dispatch('auth/setUser', firebaseUser.user)
                }).catch((error) => {
                    this.$store.commit('setError', {message: 'User not found!'}, { root: true })
                })
        } catch (e) {
            commit('setError', e, { root: true })
            throw e
        }
    }
```

**Comment by lupas** [comment]
@ruslanraupoff 

Okay, that means there is no issue with the setup, so we can ignore nuxt.config.js.

Ah I think I see the issue.... let's see:

Can you do a console.log(this.$fireAuth) in nuxtServerInit and see if this returns not null? If it returns an object everything is working fine.

this.$fireAuth.currentUser **ALWAYS return null if the user is not logged in**. And since you call it on server-side, there is most likely no user logged in yet. This is meant to happen client-side with Firebase.

Let me know if that was the issue, if yes you probably want to rethink your authentication process.

**Comment by ruslanraupoff** [comment]
@lupas 
problem only in nuxtServerInit
console.log(this.$fireAuth) return null, console.log(ctx.$fireAuth) and console.log(ctx.app.$fireAuth) too

**Comment by lupas** [comment]
@ruslanraupoff 

Hmm I'm out of ideas. Can you check if you have installed the latest versions of nuxt, nuxt-fire and firebase? Just to be sure that's not the issue.

**Comment by ruslanraupoff** [comment]
@lupas 
"nuxt": "^2.10.2",
"firebase": "^7.2.1",
"nuxt-fire": "^2.3.0",

**Comment by ruslanraupoff** [comment]
I change code after refresh page not get the current user
store/index.js
```
    nuxtServerInit({ dispatch }) {
        dispatch('auth/autoLogin')
    }
```
store/auth.js autoLogin action
```
    autoLogin({ dispatch }) {
        const user = this.$fireAuth.currentUser
        console.log(user)
        dispatch('setUser', user)
    }
```
or
```
autoLogin({ dispatch }) {
    this.$fireAuth.onAuthStateChanged(user => {
        if (user) {
            dispatch('setUser', user)
        }else {
            dispatch('logout')
        }
    })
}
```

**Comment by lupas** [comment]
> I change code after refresh page does not work get the currentUser or onAuthStateChanged
> store/index.js
...
> 

I don't know what the issue with the nuxtServerInit was, but this.$fireAuth.currentUser on server-side twill never return currentUser, the currentUser object will always be null on server-side.

If you want to make that work, you would have to work with session cookies or service workers. Read here:
https://medium.com/@hiranya911/firebase-introducing-session-cookies-for-server-side-web-apps-fb46cce40b2

The **onAuthStateChanged** approach will be easier. Here I would suggest you to create a nuxt.js plugin that gets executed on client-side only (no-ssr: true), you can follow the tutorial here:
https://hackernoon.com/vue-nuxt-firebase-auth-database-ssr-example-tutorial-facebook-login-setup-authentication-starter-app-a6dfde0133fc

Hope that helps.

This is a generic firebase & nuxt topic and not a nuxt-fire related issue anymore though, so I'll close this issue for now.
