### ISSUE TITLE
Add Remote Config service

### ISSUE THREAD

**Issue by fachrihawari** [lupas/nuxt-fire#48]
Firebase has release `remote config` beta for web. You can see this [link](https://firebase.google.com/docs/web/setup#available-libraries).

Happy coding 🚀 🚀 🚀

**Comment by lupas** [comment]
This link here is more specific for the setup of remote config:
https://firebase.google.com/docs/remote-config/use-config-web

Would be great to have that included in nuxt-fire :)

**Comment by fachrihawari** [comment]
I already made the PR #49
