### ISSUE TITLE
FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).

### ISSUE THREAD

**Issue by Suv4o** [lupas/nuxt-fire#50]
Hello There!

I have an issue with my Safari Desktop and Safari iOS. I keep receiving the following error message in the console "**FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).**". In the nuxt.config.js. file I only use the following functions --> "**useOnly: ['auth', 'firestore', 'functions', 'storage']**". I don't know how to get around this issue. I hope you have better idea how to fix it. Thanks in advance!

**Comment by Suv4o** [comment]
Sorry for the message above! I fixed it. I have installed older version (2.0.0). I updated and now is working perfectly fine. Thank you very much!

**Comment by lupas** [comment]
@Suv4o 

Are you still getting them error message with the most current version of nuxt-fire? If so, please let . us know.

Deleting node_modules and package-lock.json and then reinstallingt all modules with `npm i`  might solve the problem.

**Comment by lupas** [comment]
see also https://github.com/lupas/nuxt-fire/issues/57

**Comment by Suv4o** [comment]
Still works fine here. Since I updated to the newer version, I have't got any issues.

**Comment by lupas** [comment]
@Suv4o 
Glad to hear that, thanks for the Feedback :)
