### ISSUE TITLE
Chrome Warning - A cookie associated with a cross-site

### ISSUE THREAD

**Issue by Suv4o** [lupas/nuxt-fire#52]
I recently started receiving this Warning in my Google Chrome Console --> 

**_"A cookie associated with a cross-site resource at http://firebasestorage.googleapis.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032."_** 

Is it something that I need to worry about?

**Comment by lupas** [comment]
Thanks for reporting,

Started getting these, too. I will have a look at the cause and see if we can/have to fix something. I think at this point you won't need to hurry, well make sure if there is something to fix this module will adapt to it quickly.

What I did for now (for me) is hide the warnings temporarily by adding the following to the DevTools filter:
```
-SameSite=None
```

**Comment by lupas** [comment]
More infos:
https://www.chromium.org/updates/same-site

Will be implemented on February 4, 2020, so plenty of time.
I assume the Firebase SDK will fix this internally so we don't have to bother  about it.  Let's see  and wait if the warning goes way with  a future Firebase SDK update.

**Comment by Suv4o** [comment]
Thank you for the quick response. Hopefully the Firebase SDK will fix it by that time.
