### ISSUE TITLE
Feedback Needed: initAuth

### ISSUE THREAD

**Issue by lupas** [lupas/nuxt-fire#53]
With [v2.4.0](https://github.com/lupas/nuxt-fire/releases/tag/v2.4.0) we implemented the initAuth feature that starts the onAuthStateChanged() listener and defines vuex mutations/actions that will be called when authStateChanged.

In my case this feature is helping me reduce boilerplate code in my applications, since I don't have to manually set up a firebaseClientInit.js plugin with the same code in every application.

I haven't had enough time to test it properly, but it works very well for me so far. I put it in experimental mode since I couldn't test every case, so I would be happy to hear your thoughts of it and if you see any way to improve it (e.g. better error handling?).

The code is simple, it's basically just injecting a plugin as seen [here](https://github.com/lupas/nuxt-fire/blob/master/plugins/initAuth.js).

Any feedback is welcome, even if it works perfectly for you. Thanks :)

**Comment by aseidma** [comment]
Works great in our Application so far! Thanks again for the help provided in your Medium Article.

However, unless `export const strict = false` is set to false, I keep getting the good old `Error: [vuex] Do not mutate vuex store state outside mutation handlers` error.

I suspect it might have something to do with the code in the plugin, as my store is otherwise currently quire empty except for these two mutations and the state.

`export const strict = false

export const state = () => ({
    user: null,
    claims: null,
    error: null
})

export const mutations = {
    ON_SUCCESS_MUTATION: (state, { authUser, claims }) => {
        state.user = authUser;
        state.claims = claims;
      },
    ON_ERROR_MUTATION: (state, error) => {
        state.error = error;
    }
}`

Setting `strict = false` resolves the errors, however it does not deal with the root cause of the problem.

Otherwise, it works great and I can finally obtain and use my user object, even on refresh!

**Comment by lupas** [comment]
Hey @aseidma 

Glad it works! And sure, happy to help :)

Hm you wouldn't set const strict to false in any case if I were you, and you shouldn't need to.

This doesn't sound like an issue of nuxt-fire, its more likely that you, somewhere outside of the store, access the state and then change it without using a mutation.

Do you somewhere do something like that:
```js
this.$store.state.foo = 'test'
```

Or push to an array, or put a state variable into a function or framework that might change it directly?

If not maybe share some of your code that might affect this, because I can't see where nuxt-fire could throw that message...

**Comment by aseidma** [comment]
So I've done some digging and actions inside the mutation handlers are causing this.

My code looks like this:
`export const state = () => ({
    user: null,
    claims: null,
    error: null
})

export const mutations = {
    ON_SUCCESS_MUTATION(state, { authUser, claims }) {
        state.user = authUser;
        state.claims = claims;
      },
    ON_ERROR_MUTATION(state, error) {
        state.error = error;
    }
}`

Once I comment out `state.user = authUser` etc., the error is gone. Maybe I'm missing something here, but I'm pretty sure that's the way I've always applied mutations in the past.

**Comment by lupas** [comment]
Hm... that looks alright to me.

I'm doing it similarly with nuxt-fire, the auth option & strict=true and never got the `[vuex] Do not mutate vuex store state outside mutation handlers` error, so I wonder what it could be - since this IS in fact a mutation the error should not appear because of these lines within a mutation ^^'... hmmm.

Can you check if it is ANY of these three variables (user, claims, error) or if it is ONLY authUser? Try to narrow it down... but I still think the error should lie somewhere OUTSIDE of the store. Can you comment out every usage of these state variables and outside of the store and see if it still throws the error?

**Comment by aseidma** [comment]
Narrowed it down to `state.user = authUser`, the rest seems to work just fine. 
I have not found any instances of user, state.user or authUser outside the store that had any impact on the error thrown...

**Comment by lupas** [comment]
@aseidma 

**Regarding Edit 4:**
`onSuccessMutation` is a variable that is passed through the auth.initialize.onSuccessMutation config defined by you in nuxt.config.js, so it doesn't matter how you call your mutation, it will look for the mutation name that is defined by you.

So you won't have to name it `onSuccessMutation` of course, that's just a variable in the plugin.

---

Regarding the other edits - that is weird. It sounds to me that Firebase somehow directly mutates authUser in the background for some reason. In my case this never happened and I never got that message so far.

Could you create an empty project where you do your setup the exact same way and see if the message still throws, and then share that project with me?

**Comment by aseidma** [comment]
Just created a new project and pushed it to a new repo - still throws.
Take a look: https://github.com/aseidma/initAuthError

**Comment by lupas** [comment]
Hey @aseidma 

Alright, so they way to do it is as follows:

```js
export const mutations = {
    onSuccessMutation: (state, { authUser, claims }) => {
        state.nutzer.id = authUser.uid,
        state.nutzer.email = authUser.email
        // and eveything else you really need
    }
}
```

Never save the reference to the entire authUser object into the state, because Firebase WILL update that object regularly (probably add some timestamp or something like that).

If you really want the entire object in your story, you have to clone it, it with [_.cloneDeep](https://lodash.com/docs#cloneDeep), but I don't see why you would need that?

Hope that helps :)
