### ISSUE TITLE
Initialize Firebase Authentication Providers

### ISSUE THREAD

**Issue by lupas** [lupas/nuxt-fire#54]
Create an option `initializeAuthProviders: true` that would initialize each auth provider and inject it into the context as `$fireAuthProviders`.

Something like this:
```js
/** Initialize Firebase Auth Providers */
const fireAuthProviders = {
  facebook: new firebase.auth.FacebookAuthProvider(),
  twitter: new firebase.auth.TwitterAuthProvider(),
  google: new firebase.auth.GoogleAuthProvider()
}
inject('fireAuthProviders', fireAuthProviders)
```

Maybe with an option to specify which auth providers should be initialized, e.g.:
```js
initializeAuthProviders: ['facebook','twitter']
```

**Comment by lupas** [comment]
Decided not to implement this.

**Reason:**
Auth Providers are generally only used once and in small parts of the application, such as the login/logout view. Adding this to the global scope would not be smart, and since it is only one line of code we don't really make life easier for anyone.

**Comment by krystian50** [comment]
@lupas Any tip on how to use this library for login through Google Oauth provider? There's no info about it in docs. Only local strategy. Also, I'm trying to do it with `new firebase.auth.GoogleAuthProvider()`, but somehow the library does not recognize logged user (after coming back).

**Comment by lupas** [comment]
@krystian50 

We don't specifically talk about it in the docs because using this module does not really change anything when it comes to Auth Providers. How to access FirebaseAuth and it's object is described [here](https://firebase.nuxtjs.org/guide/usage/#examples). 

You access the Firebase Auth instance with `this.$fireAuth` and the auth object itself with `this.$fireAuthObj`.

So you can do the following:

```js
const provider = new this.$fireAuthObj.GoogleAuthProvider()
await this.$fireAuth.signInWithRedirect(provider)
```

Notice the `Obj`.

**Comment by ctwhome** [comment]
Hi @lupas , tho it is true you don't do anything with providers in the library, it wouldn't be bad to include some references in the docs, it toke me a while to discover this issue find the solution.

**Comment by lupas** [comment]
@ctwhome 
I agree, I'm thinking about rewamping the docs anyway someday soon, I'll make sure this gets covered better. Thanks for the input!

**Comment by dosstx** [comment]
Another vote for updating the docs to include the above comments. I had to search around a bit. Thank you.

**Comment by lupas** [comment]
@dosstx 
Put it on my ToDo list here https://github.com/nuxt-community/firebase-module/issues/298, will be done probably directly with the new docs. Thanks for the upvote.
