### ISSUE TITLE
Was v2.5.5 created incorrectly on NPM?

### ISSUE THREAD

**Issue by developius** [lupas/nuxt-fire#58]
Hi, just trying to update my app to use [`v2.5.5`](https://github.com/lupas/nuxt-fire/releases/tag/v2.5.5) of this package.

It looks like that tag doesn't exist on NPM, but `v2.4.5` does. GitHub doesn't have `v2.4.5` though, only `v2.4.4` and `v2.5.5`.

Did the version on NPM miss the major version bump?

Cheers

**Comment by lupas** [comment]
@developius 

Hi Developius

Thanks for pointing this out!

This is simply a typo in the release notes, the current version is supposed to be v.2.4.5, not v2.5.5. I just fixed it in the release notes.

Thanks & have a good day!

**Comment by developius** [comment]
@lupas awesome 🚀
