### ISSUE TITLE
Suggestion: Add localhost test option for cloud functions

### ISSUE THREAD

**Issue by Ferrasil** [lupas/nuxt-fire#64]
Hi, I have changed it for myself, but maybe it might be helpful to add "functions().useFunctionsEmulator()" for functions support, something like
`  
if (options.services.functions.localTest) {
        fireFunc.useFunctionsEmulator('http://localhost:${options.services.functions.localTest}')
      }
`

**Comment by lupas** [comment]
Awesome, thanks for the suggestion!
Has been added and published with NPM [v3.3.0](https://github.com/lupas/nuxt-fire/releases/tag/v3.3.0)
