### ISSUE TITLE
Fetch data from Firestore (SSR)

### ISSUE THREAD

**Issue by ToonMoon** [lupas/nuxt-fire#89]
When i try to read the database with fetch, $fireStore is undefined. Do i miss something ?

How to read firestore with asyncData or fetch ?

Have a nice day :)

**Comment by ToonMoon** [comment]
My mistake sorry :) I close the thread

**Comment by StarWar** [comment]
@ToonMoon How did you accessed firestore in asyncdata? I've tried several things including using a store action and dispatching it. It didn't work.

**Comment by lupas** [comment]
@StarWar 
Try this:
```js
  async asyncData({ app, params, error }) {
    app.$fireStore.doc('foo')
  }
```

**Comment by StarWar** [comment]
@lupas I tried the following and it didn't work. I'm new to vuejs & nuxt.

```
asyncData({ app, params, error }) {
    const docRef = app.$fireStore
      .collection('profiles')
      .doc(`${params.id}`)
    docRef.get().then((doc) => {
      return {
        profile: doc.data()
      }
    })
  },
```

**Comment by lupas** [comment]
@StarWar 
If you do the following, what does the error message say?
```js
  async asyncData({ app, params, error }) {
    const docRef = app.$fireStore.collection('profiles').doc(`${params.id}`)
    try {
      const doc = await docRef.get()
      return {
        profile: doc.data()
      }
    } catch (e) {
      console.error(e)
    }
  },
```

**Comment by StarWar** [comment]
@lupas It says Maximum call stack size exceeded

first frame from top when expanded says:-

`file: node_modules/@nuxt/devalue/dist/devalue.cjs.js`
`line highlighted: 220 `

 ```
return /^[_$a-zA-Z][_$a-zA-Z0-9]*$/.test(key) ? key : escapeUnsafeChars(JSON.stringify((key)));

```

**Comment by lupas** [comment]
**@nuxt/devalue** is another package that has nothing to do with Nuxtjs/Firebase. Seem like there is something else in your project that does not work properly... If you can provide a full repo I might be able to help you more, but that error message has nothing to do with the code you mentioned above.

**Comment by StarWar** [comment]
@lupas I've checked again, the code you mentioned does work when I navigate using links, when I refresh the page, it doesn't work

**Comment by StarWar** [comment]
@lupas In my terminal I'm seeing following warnings:


 WARN  Cannot stringify arbitrary non-POJOs Timestamp                                                         
 WARN  Cannot stringify arbitrary non-POJOs DocumentReference                                                 

I guess, the error has to do with this, it's mentioned here https://github.com/nuxt/nuxt.js/issues/6294

**Comment by lupas** [comment]
@StarWar 
Okay, that helps a bit.

So your `profile` contains a `Timestamp` and `DocumentReference` field that cannot be serialized by Nuxt. You will have to either delete these, or make them [POJO](https://www.geeksforgeeks.org/pojo-vs-java-beans/)'s.

Try this:
```js
const profile = doc.data()
profile.your_timestamp_attribute = profile.your_timestamp_attribute.toDate()
profile.your_document_reference = `${profile.your_document_reference}`   
```

Does that at least get rid of the error?

**Comment by StarWar** [comment]
@lupas Thank you so much. It did work 👍

**Comment by StarWar** [comment]
@lupas I have one more query, how should I extract the subcollections of the profile eg. addresses, education & other subcollections. Where should I add the code to query those & how should I structure the `asyncData` function in that case? They're all displayed on the same page broken into several sections... and I intend to allow editing of the sections individually using a separate form for each section which will be displayed using a modal.

**Comment by lupas** [comment]
@StarWar 
Best practice: If you most of the time need the data together with the profile anyway, DON'T put it in a subcollection. Just put address etc. it in the profile document as a map (object). Will make your life much easier.

Bear in mind that every new collection is an additional read each time, which is not really performant and will add up to your Firebase billing costs eventually.

**Comment by StarWar** [comment]
@lupas If I hadn't gotten the solution here... I might have jumped back again to using just rails and standard ssr app. I'm still giving it a shot now... so thank you :) I'm trying to use firebase as I hope that it'll cost less & heroku is costly. I'll try to put the addresses as map object. I'm taking baby steps in js land :) I will submit further queries on Stackoverflow :)

**Comment by lupas** [comment]
@StarWar 
Or text me on the [NuxtJs Discord Channel](https://t.co/8YvZaR0Q8u?amp=1), that works too ;-) Just don't wanna spam the issue board here with general Nuxt questions.

But: Stay with JS & Nuxt, it's fun :P 

On Firebase you can go quite far (e.g. about 150 users a day with about 2 hours heavy usage) and you'll still not be paying anything.

**Comment by StarWar** [comment]
@lupas I'll be prolonging my stay... if everybody's like you then this is certainly an amazing community :) I've sent you a message on discord.

**Comment by tpiros** [comment]
I was reading through this thread, but I believe I am missing something.

My setup looks like the following:

```
modules: ['@nuxtjs/firebase'],
```

I do have the config, and I have also set `firestore: true` in it.

Interestingly enough in my component I am still getting `undefined` when trying to access firestore:

```
async asyncData({ app }) {
  console.log(app.$fireStore); // undefined
}
```

What could be missing? 🤔

**Comment by mfissehaye** [comment]
`app.$fireStore` is undefined inside asyncData. Please help.

```
async asyncData({ app, store: { dispatch } }) {
    app.$fireStore.collection('messages')... // this is undefined
}
```

**Comment by lupas** [comment]
@mfissehaye 
This should work. Is $fireStore working anywhere else? If not, check if nuxt.config.js is setup correctly.

**Comment by mfissehaye** [comment]
Yes yes. I am really sorry. There was a problem with nuxt.config.js. Than you so much.

**Comment by kpe** [comment]
when I use $fireStorage in asyncData the next dev server is exiting with:
```
        this.xhr_ = new XMLHttpRequest();
                        ^

ReferenceError: XMLHttpRequest is not defined
    at new NetworkXhrIo (/home/kpe/priv.proj/proj/node_modules/@firebase/storage/dist/index.cjs.js:604:25)
    at XhrIoPool.createXhrIo (/home/kpe/priv.proj/proj/node_modules/@firebase/storage/dist/index.cjs.js:731:16)
    at doTheRequest (/home/kpe/priv.proj/proj/node_modules/@firebase/storage/dist/index.cjs.js:3246:34)
    at Timeout._onTimeout (/home/kpe/priv.proj/proj/node_modules/@firebase/storage/dist/index.cjs.js:3113:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! proj@1.5.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blinkoff@1.5.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
I don't understand, why does the code executed on the server site? How can I make it execute in the browser only?

**Comment by lupas** [comment]
@kpe 
AsyncData is meant to fetch data on the server side. See in the [offical nuxt documentation.](https://nuxtjs.org/api#__layout)

If you want to load data only on client-side, just do your stuff either in e.g. the `mounted()`hook or use `if (process.client === true) {}`
